# Generated by Django 4.1.2 on 2022-11-30 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.RemoveField(
            model_name="historicalcustomuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="historicalcustomuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="historicalcustomuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022,
                    11,
                    30,
                    3,
                    35,
                    5,
                    784332,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is staff"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False, verbose_name="is superuser"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022,
                    11,
                    30,
                    3,
                    35,
                    5,
                    784332,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="e-mail"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is staff"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False, verbose_name="is superuser"
            ),
        ),
    ]
