# Generated by Django 4.1.3 on 2022-11-30 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 3, 35, 33, 489348, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 3, 35, 33, 489348, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
