# Generated by Django 4.1.3 on 2022-11-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_avatar_historicalcustomuser_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalcustomuser",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="historicalcustomuser",
            name="name",
        ),
    ]
