# Generated by Django 4.1.4 on 2022-12-19 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 4, 20, 44, 42722, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 4, 20, 44, 42722, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
