---
version: "3.8"

services:
  db:
    container_name: training_db
    image: "postgres:14"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always

  app:
    container_name: training_app
    depends_on:
      - db
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/code/
    restart: always

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
