---
version: "3.8"

services:
  db:
    container_name: training_db
    image: postgres:14
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - internal_network
    restart: unless-stopped

  cache:
    container_name: training_cache
    image: redis:7
    networks:
      - internal_network
    env_file:
      - .env

  web:
    container_name: training_web
    image: training:latest
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal_network
      - external_network
    ports:
      - "${APP_PORT:-8000}:8000"

  celery:
    container_name: training_celery
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - web
      - cache
    volumes:
      - .:/code/
    env_file:
      - .env
    command: celery worker --app=celery:app -l INFO

networks:
  external_network:
  internal_network:

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
