---
version: "3.8"

x-app: &training-app
  depends_on:
    - db
  build: .
  env_file:
    - .env
  volumes:
    - .:/code/
  restart: always

services:
  db:
    container_name: training_db
    image: "postgres:14"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always

  web:
    <<: *training-app
    container_name: training_web
    ports:
      - "${APP_PORT:-8000}:8000"

  tailwind:
    <<: *training-app
    container_name: training_web_tailwind
    depends_on:
      - web
    command: "python manage.py tailwind start"
    tty: true

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
