# Generated by Django 4.1.3 on 2022-11-09 08:43

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        TrigramExtension(),
    ]
