# Generated by Django 4.1.3 on 2022-11-16 06:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import hashid_field.field
import mptt.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_customuser_name_customuser_deleted_at_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('coach_notes', models.TextField(blank=True, null=True, verbose_name="coach's notes")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='exercise name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.exercisecategory')),
            ],
            options={
                'verbose_name_plural': 'exercise categories',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='exercise name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='exercise description')),
                ('is_private', models.BooleanField(default=False, verbose_name='is_private')),
                ('categories', models.ManyToManyField(blank=True, to='project.exercisecategory', verbose_name='list of categoies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='name')),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='images/')),
                ('is_private', models.BooleanField(default=False, verbose_name='is_private')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='project.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammeSession',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('session_type', models.IntegerField(blank=True, choices=[(10, 'Morning'), (20, 'Afternoon'), (30, 'Evening')], null=True, verbose_name='session type')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='time start of session')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='time end of session')),
                ('coach_notes', models.TextField(blank=True, null=True, verbose_name="coach's pre training session notes")),
            ],
            options={
                'ordering': ['-date', 'session_type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.profile', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.profile', verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'coaches',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='name')),
                ('avatar', models.TextField(blank=True, max_length=100, null=True)),
                ('is_private', models.BooleanField(default=False, verbose_name='is_private')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical profile',
                'verbose_name_plural': 'historical profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExerciseSet',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True)),
                ('sets', models.PositiveIntegerField(blank=True, default=1, verbose_name='sets')),
                ('repetitions', models.PositiveIntegerField(verbose_name='repetitions')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='weight')),
                ('weight_unit', models.CharField(blank=True, choices=[('KG', 'kilograms (kg)'), ('LBS', 'pounds (lbs)'), ('PER', 'percentage (%)'), ('RPE', 'rate of perceived exertion (RPE)')], default='KG', max_length=3, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('intended', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.exercise', verbose_name='intended exercise')),
                ('outcome', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.exercise', verbose_name='outcome exercise')),
            ],
            options={
                'verbose_name': 'historical exercise set',
                'verbose_name_plural': 'historical exercise sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExerciseCategory',
            fields=[
                ('reference_id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='exercise name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.exercisecategory')),
            ],
            options={
                'verbose_name': 'historical exercise category',
                'verbose_name_plural': 'historical exercise categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExercise',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True)),
                ('coach_notes', models.TextField(blank=True, null=True, verbose_name="coach's notes")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('exercise_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.exercisetype', verbose_name='exercise_type')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.programmesession', verbose_name='Programming sessions')),
            ],
            options={
                'verbose_name': 'historical exercise',
                'verbose_name_plural': 'historical exercises',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True)),
                ('content', models.TextField(verbose_name='content')),
                ('author_object_id', models.PositiveIntegerField(null=True)),
                ('location_object_id', models.PositiveIntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author_ct', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'app_label': 'project', 'model__in': ('coach', 'athlete')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='author')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location_ct', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'app_label': 'project', 'model__in': ('exercise', 'programmesession')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='location')),
            ],
            options={
                'verbose_name': 'historical comment',
                'verbose_name_plural': 'historical comments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCoach',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'historical coach',
                'verbose_name_plural': 'historical coaches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAthlete',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'historical athlete',
                'verbose_name_plural': 'historical athletes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('sets', models.PositiveIntegerField(blank=True, default=1, verbose_name='sets')),
                ('repetitions', models.PositiveIntegerField(verbose_name='repetitions')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='weight')),
                ('weight_unit', models.CharField(blank=True, choices=[('KG', 'kilograms (kg)'), ('LBS', 'pounds (lbs)'), ('PER', 'percentage (%)'), ('RPE', 'rate of perceived exertion (RPE)')], default='KG', max_length=3, null=True)),
                ('intended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intended', to='project.exercise', verbose_name='intended exercise')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='project.exercise', verbose_name='outcome exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.exercisetype', verbose_name='exercise_type'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='programme_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.programmesession', verbose_name='Programming sessions'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='content')),
                ('author_object_id', models.PositiveIntegerField(null=True)),
                ('location_object_id', models.PositiveIntegerField(null=True)),
                ('author_ct', models.ForeignKey(limit_choices_to={'app_label': 'project', 'model__in': ('coach', 'athlete')}, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='contenttypes.contenttype', verbose_name='author')),
                ('location_ct', models.ForeignKey(limit_choices_to={'app_label': 'project', 'model__in': ('exercise', 'programmesession')}, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='contenttypes.contenttype', verbose_name='location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('athletes', models.ManyToManyField(blank=True, to='project.athlete', verbose_name='list of athletes')),
                ('coaches', models.ManyToManyField(blank=True, to='project.coach', verbose_name='list of coaches')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to='project.coach', verbose_name='creator of team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programmesession',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.athlete', verbose_name='athlete'),
        ),
        migrations.AddField(
            model_name='programmesession',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.coach', verbose_name='coach'),
        ),
        migrations.CreateModel(
            name='HistoricalTeam',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.coach', verbose_name='creator of team')),
            ],
            options={
                'verbose_name': 'historical team',
                'verbose_name_plural': 'historical teams',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProgrammeSession',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True)),
                ('date', models.DateField(verbose_name='date')),
                ('session_type', models.IntegerField(blank=True, choices=[(10, 'Morning'), (20, 'Afternoon'), (30, 'Evening')], null=True, verbose_name='session type')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='time start of session')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='time end of session')),
                ('coach_notes', models.TextField(blank=True, null=True, verbose_name="coach's pre training session notes")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('athlete', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.athlete', verbose_name='athlete')),
                ('coach', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.coach', verbose_name='coach')),
            ],
            options={
                'verbose_name': 'historical programme session',
                'verbose_name_plural': 'historical programme sessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExerciseType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='exercise name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='exercise description')),
                ('is_private', models.BooleanField(default=False, verbose_name='is_private')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.coach', verbose_name='creator')),
            ],
            options={
                'verbose_name': 'historical exercise type',
                'verbose_name_plural': 'historical exercise types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='project.coach', verbose_name='contributors'),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_type_creator', to='project.coach', verbose_name='creator'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author_ct', 'author_object_id'], name='project_com_author__d49fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['location_ct', 'location_object_id'], name='project_com_locatio_ced387_idx'),
        ),
        migrations.AddField(
            model_name='coach',
            name='athletes',
            field=models.ManyToManyField(blank=True, to='project.athlete', verbose_name='athletes'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='coaches',
            field=models.ManyToManyField(blank=True, to='project.coach', verbose_name='coaches'),
        ),
    ]
