# Generated by Django 4.1.3 on 2022-12-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetype',
            name='contributors',
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='starred',
            field=models.ManyToManyField(blank=True, to='project.coach', verbose_name='starred'),
        ),
    ]
