# Generated by Django 4.1.3 on 2022-11-11 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="project_com_content_e22fca_idx",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="object_id",
            new_name="author_object_id",
        ),
        migrations.RenameField(
            model_name="historicalcomment",
            old_name="object_id",
            new_name="author_object_id",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="intended_sets",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="outcome_sets",
        ),
        migrations.RemoveField(
            model_name="historicalcomment",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="historicalexercise",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="historicalexercise",
            name="intended_sets",
        ),
        migrations.RemoveField(
            model_name="historicalexercise",
            name="outcome_sets",
        ),
        migrations.RemoveField(
            model_name="historicalprogrammesession",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="historicalprogrammesession",
            name="exercises",
        ),
        migrations.RemoveField(
            model_name="programmesession",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="programmesession",
            name="exercises",
        ),
        migrations.AddField(
            model_name="comment",
            name="author_ct",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": ("project.Coach", "project.Athete")
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="contenttypes.contenttype",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="location_ct",
            field=models.ForeignKey(
                limit_choices_to={
                    "model__in": (
                        "project.Exercise",
                        "project.ProgrammSession",
                    )
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="contenttypes.contenttype",
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="location_object_id",
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="programme_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.programmesession",
                verbose_name="Programming sessions",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exerciseset",
            name="intended",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intended",
                to="project.exercise",
                verbose_name="intended exercise",
            ),
        ),
        migrations.AddField(
            model_name="exerciseset",
            name="outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcome",
                to="project.exercise",
                verbose_name="outcome exercise",
            ),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="author_ct",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "model__in": ("project.Coach", "project.Athete")
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="location_ct",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "model__in": (
                        "project.Exercise",
                        "project.ProgrammSession",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="location_object_id",
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalexercise",
            name="programme_session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.programmesession",
                verbose_name="Programming sessions",
            ),
        ),
        migrations.AddField(
            model_name="historicalexerciseset",
            name="intended",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.exercise",
                verbose_name="intended exercise",
            ),
        ),
        migrations.AddField(
            model_name="historicalexerciseset",
            name="outcome",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.exercise",
                verbose_name="outcome exercise",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.exercisetype",
                verbose_name="exercise_type",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="weight_unit",
            field=models.CharField(
                choices=[("KG", "kilograms"), ("LB", "pounds")],
                default="KG",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexercise",
            name="exercise_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.exercisetype",
                verbose_name="exercise_type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalexercise",
            name="weight_unit",
            field=models.CharField(
                choices=[("KG", "kilograms"), ("LB", "pounds")],
                default="KG",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprogrammesession",
            name="coach_notes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="coach's pre training session notes",
            ),
        ),
        migrations.AlterField(
            model_name="programmesession",
            name="coach_notes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="coach's pre training session notes",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author_ct", "author_object_id"],
                name="project_com_author__d49fa5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["location_ct", "location_object_id"],
                name="project_com_locatio_ced387_idx",
            ),
        ),
    ]
