# Generated by Django 4.1.3 on 2022-12-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_exercisetype_contributors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmesession',
            options={'ordering': ['-date', '-session_type']},
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='author_idx',
            old_name='project_com_author__d49fa5_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='location_idx',
            old_name='project_com_locatio_ced387_idx',
        ),
    ]
