# Generated by Django 4.1.4 on 2022-12-19 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_exercise_order_exerciseset_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogrammesession',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='is draft'),
        ),
        migrations.AddField(
            model_name='programmesession',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='is draft'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.exercisetype', verbose_name='exercise'),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='exercise_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.exercisetype', verbose_name='exercise'),
        ),
        migrations.AlterField(
            model_name='historicalprogrammesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 4, 20, 44, 161182, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='programmesession',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 19, 4, 20, 44, 161182, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
    ]
