# Generated by Django 4.1.3 on 2022-11-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0010_alter_exerciseset_weight_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='location_ct',
            field=models.ForeignKey(limit_choices_to={'app_label': 'project', 'model__in': ('exercise', 'programmesession')}, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='contenttypes.contenttype', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='location_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='author_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='location_ct',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'app_label': 'project', 'model__in': ('exercise', 'programmesession')}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='location_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
