---
name: Build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build app and run tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install-python
        name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pipenv

      - id: install-pipenv
        name: Install pipenv
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv

      - id: install-dependancies
        name: Install dependencies
        run: |
          pipenv sync --dev --python ${{ steps.install-python.outputs.python-version }}

      - id: test-tox
        name: Test with tox
        run: |
          python -m pip install tox tox-gh-actions
          tox
